### ISSUE TITLE
404 on http://cocoadocs.org/docsets/Datavenue/0.1.0/

### ISSUE THREAD

**Issue by yalp** [CocoaPods/cocoadocs.org#338]
Hi guys,

I'm getting a 404 since yesterday for a new pod: http://cocoadocs.org/docsets/Datavenue/0.1.0/
and I can't get http://api.cocoadocs.org:4567/error/Datavenue/0.1.0 to answer me...

I tried the preview command `bundle exec ./cocoadocs.rb preview Datavenue 0.1.0` to check if it could come from the project itself, but it works fine localy.

Could it be because the 0.1.0 ref is branch instead of a tag ?

Thanks for your help.

**Comment by kylef** [comment]
This has been built now. I think it just took a while.

![screen shot 2015-05-07 at 10 29 42](https://cloud.githubusercontent.com/assets/44164/7512298/025f4908-f4a4-11e4-9528-cf1ab9b98063.png)

**Comment by yalp** [comment]
Ok, thanks.

**Comment by orta** [comment]
I did this manually to test the ranch theory ( which was a good guess @yalp ) - which fixed it.
I think CocoaDocs was having server hiccups due to a bug around the response type, which I've fixed and deployed, https://github.com/CocoaPods/cocoadocs.org/commit/f6f7cc0a8d6d671191a68ea98aae4709aed7fab5
