### ISSUE TITLE
CocoaDocs has too many hard dependencies on CocoaPods infrastructure

### ISSUE THREAD

**Issue by jcayzac** [CocoaPods/cocoadocs.org#375]
you know what, never mind.

**Comment by segiddins** [comment]
@jcayzac a PR helping make the option more useful would be awesome!

**Comment by jcayzac** [comment]
No time. Looking at http://www.github.com/realm/jazzy

**Comment by orta** [comment]
If you're just looking to generate documentation for a single project, you can [use appledoc](http://appledoc.gentlebytes.com) which CocoaDocs sits on top of for obj-c projects.

But yeah, there's a few dependencies on CP projects because no-one else uses it for anything else.

**Comment by jcayzac** [comment]
@orta Thanks. I wish appledoc would parse a project's podspec instead of having to pass file patterns…

> there's a few dependencies on CP projects because no-one else uses it for anything else.

Not working for anything else but public pods might be the reason :)

**Comment by orta** [comment]
So, @jcayzac I'll be frank, this is a pretty passive aggressive message you're sending. It's not going to work. 

I have worked on CocoaDocs for 2 and a half years, making fundamental infrastructure for all Cocoa libraries. The Jazzy crew have been doing the same, on a smaller timescale. I saw your comments over there. Saying: things like:

>  "Not working for anything else but public pods might be the reason :) " 

is not a positive way of implying I should spent my free time working on something that _could_ work out in someone else's favour. I'd love people to use CocoaDocs in their larger structure, but until someone shows some effort to make things better it's not worth my time to do it. Please be more respectful of the people whose time you are asking for.

**Comment by jcayzac** [comment]
@orta Wow that was never intended as an aggressive message. What is wrong with that message you copy/pasted? It states a truth, signals interest in using your work more broadly, and hints at a direction for making that happen. It's fucking positive IMO (yes, I'm getting pissed at you getting pissed, now).

You're doing a great job and I've been using a number of your projects, but getting aggressive any time somebody make some constructive criticism isn't going to help. Guess I won't be sending any PR your way.

**Comment by orta** [comment]
It's more that I have at multiple points offered the chance for others to collaborate and make things work for them, it has not worked out, so those customization points are there. 

Implying that because I'm not offering a full-blown solutions for everyone to build their own infrastructure off my community work isn't enough for people to start contributing back isn't helping.

Changing the issue title is also passive aggressive. Your initial point is legit, I focus on the community aspect of CocoaDocs. That is _my_ focus. CocoaDocs can work for people who are not me, running CocoaPods' infrastructure, but that's the problems I face. Help this project by making these things  optional is a way to improve things for everyone.

**Comment by jcayzac** [comment]
Something that isn't immediately clear to me is the reason for calling the cocoapods' API in order to gather a spec's versions, rather than just looking at the versions available in the local copy of the spec repo that the tool has just checked out. Is it just for convenience, as the API returns some nice JSON structured data?

**Comment by orta** [comment]
Closing, as I'm not sure anyone is ever going to do this now.
