### ISSUE TITLE
GitHub README.me Missing Sections on CocoaPods.org

### ISSUE THREAD

**Issue by iosdevzone** [CocoaPods/cocoadocs.org#401]
The README.md from GitHub (which renders fine there) is missing the sections on (ironically enough) installing using CocoaPods and Carthage. 

Compare https://cocoapods.org/pods/IDZSwiftCommonCrypto with https://github.com/iosdevzone/IDZSwiftCommonCrypto/tree/swift2.0

**Comment by orta** [comment]
That's on purpose, we remove all installation sections and badges etc.

**Comment by iosdevzone** [comment]
Totally breaks flow of doc and confusing for user, but if you must!

**Comment by orta** [comment]
I've not been able to think of a safe way to remove the manual sections too, which would be ideal also alas.

**Comment by iosdevzone** [comment]
I mean, I see where you are coming from... but it seems it is easier for users to skip over a complete, coherent Installation section than a confusing hacked one. I suppose I can just put a note in mentioning that some sections will be hidden on CocoaPods.org

**Comment by orta** [comment]
It gets boring quickly when you're searching through a bunch of pods and you have to scroll through 8-9 paragraphs you already know for every pod you want to compare. In your case I'd see one sentence, then many paragraphs before I can find out anything relevant to the project vs how to integrate it. 

There might be value in adding something to the `.cocoapods.yml` file we've slowly started working towards to skip this, but your instructions are not particularly unique, anyone using carthage or cocoa pods knows exactly what to do there.

**Comment by iosdevzone** [comment]
Fair enough!

**Comment by shagedorn** [comment]
I think this issue deserves further discussion. I was quite upset to learn that CocoaPods manipulates the README without any notice, neither for the author nor the site visitor.

* the CocoaPods summary leaves any visitor under the impression that what he sees on the first page is solely provided by the library author
    * is says `README` at the top, so I think users expect to be presented the original README file
    * there is no notice that any content may have been changed automatically - not on that site, nor in any FAQ

* removing the CocoaPods section is problematic is you use that section to describe your sub specs rather than just the general install instructions

* removing the Carthage section (and badge) is bad style for a project that prides itself for openness. It reminds me of Apple preventing you from mentioning "Android" (or any other platform) in your App Store description, but they will at least tell you about this and make you remove it, rather than silently censoring/changing it behind your back

* I'm not a lawyer, but I'm not sure if every OS license allows you to change files and then claim that the original author published it that way (see first point), when in fact it was published differently.

I believe you should either give it a different title (other than `README`), or provide a hint that it is not what the author has written originally. Or just remove the code that removes those sections and badges.

**Comment by orta** [comment]
> is says README at the top

It took me a while to figure out what this was referring to, but it's this selector, which only shows when there's a parsed CHANGELOG:

<img width="773" alt="screen shot 2016-07-18 at 06 25 43" src="https://cloud.githubusercontent.com/assets/49038/16912137/7ad53ac2-4cb0-11e6-8799-6adbcb70c475.png">

I'm open to changing the wording, but I'm not sure it's a legal requirement, part of the T&C for uploading something to trunk is that we need to make data transformations in-order to present information on the websites / API. This is normal, and the same as most websites, it to cover things like resizing images, rendering markdown etc.

We keep Carthage, and Swift Package Management information on the left with all the other useful metadata, and also expose it in our API too so others can use this. It's redundant information on the page, and as with all badges they're pretty noisy - a lot of information is a subset of what we show on the metadata section.

If the parser notices that you talk about subspecs it shouldn't be removing sections, if it is that's a bug and I'd love an example to add some tests against 👍

**Comment by shagedorn** [comment]
Thanks for responding so quickly.

I don't have any problem with adjustments that are purely technical. The readers won't notice the difference, so I believe this is very different from content adjustments.

> We keep Carthage, and Swift Package Management information on the left with all the other useful metadata

What page are you referring to? I cannot find any information "on the left" on, e.g., this page:
https://cocoapods.org/pods/ISHHoverBar

It only displays "Creates Framework" (on the right), which is not quite the same as explicitly supporting Carthage, which implies that the author has actually verified the compatibility. The GitHub page for the same release/tag is https://github.com/iosphere/ISHHoverBar/tree/1.0.1.

I can see the motivation for removing the default instructions, but not every library displays them at the top, and I believe the disadvantages/risks outweigh the gains here.

https://github.com/iosphere/ISHPermissionKit is a library where non-default CP instructions are stripped as well. We don't mention the word "subspec" (as users of the library don't necessarily need to know anything about it), but it is an important bit of information.

Knowing the code that strips certains section, we could work around it, but I don't think that's a path worth pursuing, and you probably don't want people to misspell CP as a workaround to have their install instructions displayed.

**Comment by orta** [comment]
Ah yeah, sorry, I meant the right.

> It only displays "Creates Framework" (on the right), which is not quite the same as explicitly supporting Carthage, which implies that the author has actually verified the compatibility. The GitHub page for the same release/tag is https://github.com/iosphere/ISHHoverBar/tree/1.0.1.

It does in this case, we check the README for any mention of Carthage, and if it's not found we run Carthage against the project to determine if it works or not 👍 - it's an accurate value of support.

> We don't mention the word "subspec" (as users of the library don't necessarily need to know anything about it), but it is an important bit of information.

Yeah, that's an interesting point, at least in this case I think we can do better around looking for these cases where the word subspec isn't used, perhaps looking for anything that is `pod "XXX/YYY"`.

Overall, though, I'm not in favour of removing the system, I think it significantly improves the usability of the index in favour of the occasional hiccup, and is revised and improved when we get feedback like this.

**Comment by shagedorn** [comment]
> It does in this case, we check the README for any mention of Carthage, and if it's not found we run Carthage against the project to determine if it works or not 👍 - it's an accurate value of support.

I think that's a pretty rough guesstimate. One might as well mention "Carthage" in the README without implying support (think: "TODO: Carthage support"), and provide a framework target that is not working well with Carthage. We actually do have a project that builds as framework, but is not really Carthage-compatible, because more than one framework targets builds a framework with the same filename, which is a problem. Just because Carthage does not throw an error, it doesn't mean it is working correctly either. So: Let the author decide.

I think it would be a lot clearer to call it "Carthage Support" (instead of "Creates Framework"), and check if the author has set the Carthage badge. Everything else just seems like guessing.

I would strongly prefer a title name change ("Summary" instead of "README"?), or provide a link/footnote that clarifies that it's slightly modified.

**Comment by orta** [comment]
Cool, few a bunch of these changes on the site, and the backend.

**Comment by shagedorn** [comment]
Appreciate your responsiveness!

**Comment by evgenyneu** [comment]
Hi, is there a way for me to make the Carthage setup instructions showing up on the CocoaPods page of my library?

Here is the library on Github: https://github.com/evgenyneu/SigmaSwiftStatistics

And here its CocoaPods page: https://cocoapods.org/pods/SigmaSwiftStatistics

It would be nice to keep the Carthage instructions on CocoaPods:

<img width="873" alt="screen shot 2016-09-09 at 4 53 27 pm" src="https://cloud.githubusercontent.com/assets/880411/18378073/0d13f71c-76ae-11e6-9539-77e685c9e346.png">

Thank you

**Comment by jgimenez** [comment]
What if one were able to provide a different file than the README.md, something like an OVERVIEW.md that could contain a cleaned-up version?
I agree once installed, there is no point in showing the installation instructions, but in my case it leaves the manual instructions (as @orta mentioned), which makes it super-confusing.
