### ISSUE TITLE
CocoaDocs lists classes from files which are not included in the Pod

### ISSUE THREAD

**Issue by danthorpe** [CocoaPods/cocoadocs.org#402]
Many pods contain example projects (which may including other Pods). My [Operations pod](https://cocoapods.org/pods/Operations) does this, and [the documentation](http://cocoadocs.org/docsets/Operations/2.3.0/) for its latest version lists many classes which are not included in the framework.

I guess what is happening is that the path to the jazzy is not being limited by the rules of the podspec?

![napkin 02-11-15 11 04 44 a m](https://cloud.githubusercontent.com/assets/309420/10880230/86e73f16-8151-11e5-83ae-0ce897015c00.png)

**Comment by orta** [comment]
Hrm, I wonder if this is a mix of the carthage crash we've been having for the last few weeks + #399 

So when Jazzy would crash it passes the rendering to appledoc, which starts by looking at the `public_headers` property, which is empty for an all swift project, so it finds every header file in the repo. Since I fixed all the major crashers this weekend, I re-ran your docs during my writeup and it's looking like Jazzy will be running them and everything should be :+1:

**Comment by orta** [comment]
Yep :+1: 
![screen shot 2015-11-02 at 07 24 18](https://cloud.githubusercontent.com/assets/49038/10881666/c0aeb770-8132-11e5-8deb-4970e1db8a11.png)

**Comment by danthorpe** [comment]
Oh great! Wow! I didn't quite follow what you fixed - but awesome stuff.
