### ISSUE TITLE
New releases redirect to Github page

### ISSUE THREAD

**Issue by danielpassos** [CocoaPods/cocoadocs.org#550]
Hi,

I see there is a lot of issues around the same problem, but I could not found the solution.

All my new releases are pointing to Github page instead of the CocoaPods page.

* AeroGearCrypto
* AeroGearOTP
* AeroGearPush
* AeroGearPush-Swift

**Comment by tgeorgieva** [comment]
I have the same issue. I pushed a new pod, SwiftVideoGenerator, 3 days ago. I got a message for successful publish with the date and a link to the CocoPods page. 

When I copy/pasted the link I got redirected to the project's Github page. I've tried releasing two new versions since then and neither one has been published.

When I try to install the pod in a new project I get: "Unable to find a specification for SwiftVideoGenerator"

http://cocoadocs.org/docsets/SwiftVideoGenerator opens with a 404 error.
https://cocoapods.org/pods/SwiftVideoGenerator redirects to GitHub.

I've tried releasing new versions, I waited 24 hours before I attempted a second release. I've looked at the other similar issues that are still opened but nothing helps. There is no explanation why the supposedly successful push isn't all that successful. 

If you can please look into it and help us solve the problem it'll be much appreciated.

**Comment by jcesarmobile** [comment]
@tgeorgieva for the "Unable to find a specification for xxx" try running `pod repo update` before the `pod install`

As far as I know, cocoadocs was sunset some time ago, but it's not clear to me if that means that the pages at `https://cocoapods.org/pods/PodName` won't be available neither

**Comment by tgeorgieva** [comment]
@jcesarmobile Hm, the ```pod repo update``` did the trick this time. That's the first think I tried when I first released but when it didn't work I didn't try again. I guess one of the subsequent releases must have worked out correctly :)

Yes, indeed, when I search for the ```https://cocoapods.org/pods/PodName``` for Alamofire for example, it's easy to find. I don't know if all other pages should be available or not. But for now the GitHub redirect will have to do...

Thank you for the quick response!

**Comment by Palleas** [comment]
Hi there - we're flipping the switch for the new hosting today. It will be easier to investigate from now on.

**Comment by svdo** [comment]
I had this too today for my pod [ReRxSwift](https://cocoapods.org/?q=ReRxSwift).

**Comment by jpgupta** [comment]
Same for https://github.com/MyLabs/ParseArrayHelper

**Comment by giulio92** [comment]
Same here for https://github.com/giulio92/GLColor

**Comment by Palleas** [comment]
Hi there - We are still working on adding those new versions of XCode but right now we have an issue that we hope to resolve soon. Sorry about that!

**Comment by kkvinokk** [comment]
Same here for https://cocoapods.org/pods/KKSwipeCards

**Comment by addb** [comment]
I am having the same issue of 404 for docs and redirect for the pod. What is the expected time to see the docs, info and spec loaded for a newly published pod?

**Comment by Palleas** [comment]
We're still working on it, I'll update this once we have news.

**Comment by vittalpai** [comment]
Same here https://cocoapods.org/pods/IBMAppLaunch :(

**Comment by twittemb** [comment]
Hi everyone

Same here https://cocoapods.org/pods/RxFlow

thx for the help.

**Comment by orta** [comment]
I followed the instructions in [the README](https://github.com/CocoaPods/cocoadocs.org#getting-help) for both IBMAppLaunch and RxFlow and they're now working. 👍

**Comment by orta** [comment]
For everyone else, given that Apple has bought out BuddyBuild who were going to try maintain CocoaDocs. I'll start to make it very obvious that CocoaDocs is [fully shut down](http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/) within the next few weeks like I mentioned at the start of 2017.
