### ISSUE TITLE
Docs generation failed.

### ISSUE THREAD

**Issue by pcpLiu** [CocoaPods/cocoadocs.org#556]
Cannot generate docs for project [https://github.com/pcpLiu/Serrano](https://github.com/pcpLiu/Serrano), cocoapods link: [https://cocoapods.org/?q=serrano](https://cocoapods.org/?q=serrano)

Here's some checking steps:

- [x] First up, load up the expected URL in CocoaDocs. The URL will look like [http://cocoadocs.org/docsets/Serrano/](http://cocoadocs.org/docsets/Serrano/)
**Get 404 error** 

- [x] The most common problem with generating documentation is that your library crashes either [appledoc](http://appledoc.gentlebytes.com/appledoc/) or [jazzy](https://github.com/realm/jazzy). This tends to happen when you use bleeding edge features in betas of Xcode. However, sometimes it can "just happen" generating all this documentation is a complex process, as most swift libs need to be compiled and Xcode it a tough dependency to have. 
**I generate my API using jazzy hosted on [my website](http://serrano-lib.org/docs/latest/api/), so it it should be OK to generate API via jazzy.**

- [x] The 404 page on CocoaDocs.org offers a button to request that CocoaDocs takes a second look at running your library, the URL for this is [http://api.cocoadocs.org:4567/redeploy/Serrano/latest](http://api.cocoadocs.org:4567/redeploy/Serrano/latest)
**Cannot be reached**
  
- [x] CocoaDocs also offer a way to see errors from CocoaDocs related to a pod. The URL for this [http://api.cocoadocs.org:4567/error/Serrano/0.1.2-alpha](http://api.cocoadocs.org:4567/error/Serrano/0.1.2-alpha). You'll get a 404 if there's no logged errors.
 **Cannot be reached**

**Comment by Palleas** [comment]
Hi there - We have some issues with generating doc right now, definitely something dumb that we hope to resolve asap. Sorry about that!

**Comment by pcpLiu** [comment]
@Palleas  Thanks for the information.

**Comment by ahamino** [comment]
any updates on this issue?
It affects our latest release.
https://cocoapods.org/pods/AffdexSDK-iOS

**Comment by raginmari** [comment]
I have a similar issue with my pod [RAGVersionNumber](https://github.com/raginmari/RAGVersionNumber).

What I've found out so far:

In release 0.9.0 of [jazzy](https://github.com/raginmari/RAGVersionNumber), the `download_badge` configuration key was **removed**. When I execute cocoadocs locally (described [here](http://cocoadocs.org/readme/)), the build fails because "cocoadocs.rb" uses the `download_badge` property of the jazzy config.

> undefined method 'download_badge='

If I comment out that line in "cocoadocs.rb", jazzy fails for a different reason:

Although the .jazzy.yaml is detected (terminal output says so), the version of Swift specified in the file appears to be ignored (.jazzy.yaml says "3.0.2", jazzy uses "3.0" and fails). And/but: if I use jazzy independently of cocoadocs, it succeeds.

**Comment by fjcaetano** [comment]
I'm also having this issue with my project ReCaptcha.

It seems to have something to do with domain configuration, because when trying to reparse, or fetch the error info, dev tools throws us some errors on `api.cocoadocs.org:4567`.

When I try to access http://api.cocoadocs.org:4567/error/ReCaptcha/1.0.0 directly, it fails with `ERR_NAME_NOT_RESOLVED`:
> api.cocoadocs.org’s server DNS address could not be found.

**Comment by stringeecom** [comment]
I have a similar issue with my pod.
Github: [](https://github.com/stringeecom/Stringee-iOS-SDK)
Cocoapods link: [](https://cocoapods.org/?q=Stringee)
any updates on this issue? Thank you!!

**Comment by Fenil15** [comment]
Any update on this? I am also facing this issue since last update 4 days back.

**Comment by Fenil15** [comment]
Running this command on terminal worked for me - 
curl http://199.19.84.242:4567/redeploy/<Pod name>/latest

**Comment by bosborn** [comment]
I am running into this problem for three of our libraries.  Each library has a history of successful documentation generation.
- https://cocoapods.org/pods/tiff-ios
- https://cocoapods.org/pods/wkb-ios
- https://cocoapods.org/pods/geopackage-ios

Along with the normal redeploy attempts, I tried the curl statement above.  Although I get a {"parsing":true} response, the documentation is never updated.

I am able to preview the library docs following these instructions: https://github.com/CocoaPods/cocoadocs.org#previewing-my-library-in-cocoadocs

The generated [pod]/[version]/index.html file appears correct when opened.

Side Note:  Sometime between March and June of 2017, the "Docs %" calculations stopped populating.
