### ISSUE TITLE
my project eashyshowview docsets is 404

### ISSUE THREAD

**Issue by chenliangloveyou** [CocoaPods/cocoadocs.org#573]
sit : http://cocoadocs.org/docsets/EasyShowView/1.0.0

**Comment by Sorix** [comment]
duplicate of #572

**Comment by orta** [comment]
Hi there, CocoaDocs was shut down back in [early 2017](http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/) and has been slowly stopping support for new projects. At some point we plan on making a notification on all pages about the shutdown, but for now your issue is likely to be unresolved by anyone.
